name: publish_dev
on:
    schedule:
        - cron: '*/5 * * * *'
jobs:
  publish:
    if: ${{ contains(github.ref_name, 'dev') }}
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Node.js v18
          uses: actions/setup-node@v3
          with:
            node-version: 18
            registry-url: https://registry.npmjs.org/
    
        - name: Install Dependencies
          run: npm install
        
        - name: Publish NPM
          run: |
            npm publish --provenance --no-git-checks --access public --tag dev || true
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}